---
title: "D2SC ICMA Notebook"
author: "Abhi Patel"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    toc: yes
  html_document:
    df_print: paged
    toc: yes
    toc_depth:2
    toc_float: yes
  word_document:
    toc: yes
---
# ICMA Sept 9 2024
```{r}
plot(cars)
```
# ICMA Sept 11 2024
This is where we put plain text.
```{r}
#this is where we put r code
fave_number<-12
print(fave_number)
`1number1`<-15
print(`1number1`)
ohno_this_is_a_nightmare<-"hello"

```
```{r}
2+2
```

```{r}
x<-2+2
```
```{r}
help(c)
my_vector<-c(2,3,4.666668)
mean(my_vector)
```
```{r}
sd(1:2)^2
```
# ICMA Sept 16 2924
```{r}
library(tidyverse)
getwd()
mtcars%>%
  rownames_to_column()%>%
  write_csv("mtcars_fromR_rownames.csv")
```
```{r}
mtcars_read<-read_csv("mtcars_fromR_rownames.csv")
mtcars_read
```
# ICMA Sept 18 2024
```{r}
library(tidyverse)
```
```{r}
?ChickWeight
glimpse(ChickWeight)
```
```{r}
chick_clean<-ChickWeight%>%
  select(chick_id = Chick, diet = Diet, age_days = Time, weight_gm = weight)
print(chick_clean)
```
```{r}
chick_clean%>%
  distinct(chick_id)
```
```{r}
chick_clean%>%
  mutate(weight_lbs = weight_gm/453.6) %>%
  group_by(diet,age_days)%>%
  summarise(N=n(), mean_wgt_gm = mean(weight_gm), mean_wgt_lbs = mean(weight_lbs))%>%
  filter(age_days==20)
```
```{r eval = FALSE}
chick_clean%>%
  filter(age_days==20)%>%S
  mutate(weight_lbs = weight_gm/453.6)%>%
  group_by(diet)%>%
  summarise(N=n(), mean_wgt_gm = mean(weight_gm), mean_wgt_lbs = mean(weight_lbs))

```
```{r}
mtcars_modified<-read_csv("data/mtcars_fromR_rownames.csv")
```
```{r}
glimpse(mtcars_modified)
```

# ICMA Sept 23 2024
```{r}
billboard_long<-billboard%>%
  pivot_longer(cols = starts_with("wk"), 
               names_to = "week", 
               values_to = "position")
```
```{r}
dim(billboard_long)
billboard_long%>%
  pivot_wider(names_from = week, values_from = position)
```
```{r}
billboard_long
```
```{r}
?pivot_longer
```
```{r}
billboard%>%
  pivot_longer(cols = starts_with("wk"),
               names_to = "week",
               values_to = "position",
               names_prefix = "wk",
               values_drop_na = TRUE)
```
```{r}
billboard%>%
  separate(col = date.entered, into = c("year", "month", "day") )%>%
  unite(col = "full_date", c(year, month, day), sep = "-")
```
# ICMA Sept 25 2024

```{r}
ChickWeight%>%
  ggplot(aes(y=weight,
             x=Time,
             color = Diet)) +
  geom_point(alpha=0.5) + #make these a little transparent
  geom_smooth(se = FALSE)+#removing the error bands
  theme_minimal()+#using a pre-made theme to change the appearance, which we can further modify!
  facet_grid(~Diet)+ #faceting by diet
  labs(y = "weight in grams",
       x = "days since birth",
       title = "Weight over time across diets")
ggsave("chick_weightovertime.png")
```
# ICMA Oct 7 2024
```{r}
as.integer("18.123123")
```
```{r}
my_double<-12.9
```
```{r}
as.character(my_double)
```
```{r}
2+3+9+4==2+6+as.integer("2.9") & TRUE | NA
```
# ICMA Oct 9 2024

```{r}
library(tidyverse)
age_data<-tribble(
  ~id, ~age,
  1,8,
  2,10,
  3,8,
  5,9,
)
gender_data<-tribble(
  ~id,~gender,
  1, "f",
  2, "m",
  3, "nb",
  4, "m",
  6, "f"
)
print(gender_data)
full_join(age_data,gender_data)
right_join(age_data, gender_data)
left_join(age_data, gender_data)
  


```

# ICMA Oct 16 2024
```{r}
mean(c(1,2,3))
```
```{r}
(1+2+3)/3
```
```{r}
vec<-c(1,2,3)
```
```{r}
(vec[1]+vec[2]+vec[3])/length(vec)
```
```{r}
for(i in 1:10)
{
  print(i^2)
}
```
```{r}
library(tidyverse)
library(dplyr)
fave_number<-tribble(~name, ~number,
                     "MC", 8,
                     "AP", 9,
                     "NG", 12,
                     "VE", 6,
                     "AL", 17,
                     "AR", 3,
                     "MC", 7,
                     "RK", 8,
                     "AC", 4,
                     "SC", 21,
                     "KK", 16,
                     "RK", 28,
                     "VK", 17,
                     "MH", 12)
```
Write a loop to print each fave number
```{r}
for (i in fave_number$number)
{
  print(i)
}
```
Why is the output different?
How are fave_number["number"] and fave_number$number different?
```{r}
typeof(fave_number[["number"]])
typeof(fave_number$number)
```
```{r}

```

# ICMA Oct 30 2024
```{r}
library(tidyverse)
```